// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"
	"database/sql"
)

const logAudit = `-- name: LogAudit :one
INSERT INTO audit_logs (
    user_id,
    action,
    path,
    ip_address
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, action, path, ip_address, created_at
`

type LogAuditParams struct {
	UserID    sql.NullInt32  `json:"user_id"`
	Action    string         `json:"action"`
	Path      string         `json:"path"`
	IpAddress sql.NullString `json:"ip_address"`
}

func (q *Queries) LogAudit(ctx context.Context, arg LogAuditParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, logAudit,
		arg.UserID,
		arg.Action,
		arg.Path,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Path,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}
