// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enterprise.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (name, description) VALUES ($1, $2) RETURNING id, name, description
`

type CreateDepartmentParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, createDepartment, arg.Name, arg.Description)
	var i Department
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createLeaveType = `-- name: CreateLeaveType :one
INSERT INTO leave_types (name, max_days, description) VALUES ($1, $2, $3) RETURNING id, name, max_days, description
`

type CreateLeaveTypeParams struct {
	Name        string         `json:"name"`
	MaxDays     int32          `json:"max_days"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateLeaveType(ctx context.Context, arg CreateLeaveTypeParams) (LeaveType, error) {
	row := q.db.QueryRowContext(ctx, createLeaveType, arg.Name, arg.MaxDays, arg.Description)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxDays,
		&i.Description,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (name, level) VALUES ($1, $2) RETURNING id, name, level
`

type CreatePositionParams struct {
	Name  string        `json:"name"`
	Level sql.NullInt32 `json:"level"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRowContext(ctx, createPosition, arg.Name, arg.Level)
	var i Position
	err := row.Scan(&i.ID, &i.Name, &i.Level)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteEmployee, id)
	return err
}

const deleteLeaveType = `-- name: DeleteLeaveType :exec
DELETE FROM leave_types WHERE id = $1
`

func (q *Queries) DeleteLeaveType(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLeaveType, id)
	return err
}

const getAdvancedLeaves = `-- name: GetAdvancedLeaves :many
SELECT 
  lr.id, lr.employee_id, lr.leave_type_id, lr.start_date, lr.end_date, lr.total_days,
  lr.reason, lr.attachment_url, lr.status, lr.hrd_note, lr.reviewed_by, lr.created_at,
  e.full_name as employee_name, e.department as employee_department, e.position as employee_position
FROM leave_requests lr
JOIN employees e ON lr.employee_id = e.id
WHERE 
  ($1::text = '' OR lr.status = $1)
  AND ($2::text = '' OR e.department = $2)
ORDER BY lr.created_at DESC
`

type GetAdvancedLeavesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

type GetAdvancedLeavesRow struct {
	ID                 int32          `json:"id"`
	EmployeeID         int32          `json:"employee_id"`
	LeaveTypeID        int32          `json:"leave_type_id"`
	StartDate          time.Time      `json:"start_date"`
	EndDate            time.Time      `json:"end_date"`
	TotalDays          int32          `json:"total_days"`
	Reason             string         `json:"reason"`
	AttachmentUrl      sql.NullString `json:"attachment_url"`
	Status             string         `json:"status"`
	HrdNote            sql.NullString `json:"hrd_note"`
	ReviewedBy         sql.NullInt32  `json:"reviewed_by"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	EmployeeName       string         `json:"employee_name"`
	EmployeeDepartment string         `json:"employee_department"`
	EmployeePosition   string         `json:"employee_position"`
}

func (q *Queries) GetAdvancedLeaves(ctx context.Context, arg GetAdvancedLeavesParams) ([]GetAdvancedLeavesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAdvancedLeaves, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdvancedLeavesRow
	for rows.Next() {
		var i GetAdvancedLeavesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LeaveTypeID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalDays,
			&i.Reason,
			&i.AttachmentUrl,
			&i.Status,
			&i.HrdNote,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.EmployeeName,
			&i.EmployeeDepartment,
			&i.EmployeePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT 
  (SELECT COUNT(*) FROM employees) AS total_employees,
  (SELECT COUNT(*) FROM leave_requests WHERE status = 'pending' AND DATE(created_at) = CURRENT_DATE) AS pending_today,
  (SELECT COUNT(*) FROM leave_requests WHERE status = 'approved') AS total_approved,
  (SELECT COUNT(*) FROM leave_requests WHERE status = 'pending') AS total_pending,
  (SELECT COUNT(*) FROM leave_requests WHERE status = 'rejected') AS total_rejected
`

type GetDashboardStatsRow struct {
	TotalEmployees int64 `json:"total_employees"`
	PendingToday   int64 `json:"pending_today"`
	TotalApproved  int64 `json:"total_approved"`
	TotalPending   int64 `json:"total_pending"`
	TotalRejected  int64 `json:"total_rejected"`
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalEmployees,
		&i.PendingToday,
		&i.TotalApproved,
		&i.TotalPending,
		&i.TotalRejected,
	)
	return i, err
}

const getDepartments = `-- name: GetDepartments :many
SELECT id, name, description FROM departments ORDER BY name ASC
`

func (q *Queries) GetDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, getDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaveHistories = `-- name: GetLeaveHistories :many
SELECT lh.id, lh.leave_request_id, lh.action, lh.hrd_note, lh.actor_id, lh.created_at, u.email as actor_email 
FROM leave_histories lh
JOIN users u ON lh.actor_id = u.id
WHERE lh.leave_request_id = $1
ORDER BY lh.created_at DESC
`

type GetLeaveHistoriesRow struct {
	ID             int32          `json:"id"`
	LeaveRequestID int32          `json:"leave_request_id"`
	Action         string         `json:"action"`
	HrdNote        sql.NullString `json:"hrd_note"`
	ActorID        int32          `json:"actor_id"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	ActorEmail     string         `json:"actor_email"`
}

func (q *Queries) GetLeaveHistories(ctx context.Context, leaveRequestID int32) ([]GetLeaveHistoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaveHistories, leaveRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaveHistoriesRow
	for rows.Next() {
		var i GetLeaveHistoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LeaveRequestID,
			&i.Action,
			&i.HrdNote,
			&i.ActorID,
			&i.CreatedAt,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaveRecapPerDepartment = `-- name: GetLeaveRecapPerDepartment :many
SELECT 
  d.name AS department,
  COUNT(lr.id) AS total_leaves,
  COALESCE(SUM(lr.total_days), 0)::int AS total_days
FROM departments d
LEFT JOIN employees e ON d.name = e.department
LEFT JOIN leave_requests lr ON e.id = lr.employee_id AND lr.status = 'approved'
GROUP BY d.name
ORDER BY total_leaves DESC, d.name ASC
`

type GetLeaveRecapPerDepartmentRow struct {
	Department  string `json:"department"`
	TotalLeaves int64  `json:"total_leaves"`
	TotalDays   int32  `json:"total_days"`
}

func (q *Queries) GetLeaveRecapPerDepartment(ctx context.Context) ([]GetLeaveRecapPerDepartmentRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaveRecapPerDepartment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaveRecapPerDepartmentRow
	for rows.Next() {
		var i GetLeaveRecapPerDepartmentRow
		if err := rows.Scan(&i.Department, &i.TotalLeaves, &i.TotalDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyLeaveStats = `-- name: GetMonthlyLeaveStats :many
SELECT 
  TO_CHAR(start_date, 'YYYY-MM') AS month,
  COUNT(*) AS total
FROM leave_requests
WHERE status = 'approved' AND start_date >= CURRENT_DATE - INTERVAL '6 months'
GROUP BY 1
ORDER BY 1
`

type GetMonthlyLeaveStatsRow struct {
	Month string `json:"month"`
	Total int64  `json:"total"`
}

func (q *Queries) GetMonthlyLeaveStats(ctx context.Context) ([]GetMonthlyLeaveStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlyLeaveStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyLeaveStatsRow
	for rows.Next() {
		var i GetMonthlyLeaveStatsRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPositions = `-- name: GetPositions :many
SELECT id, name, level FROM positions ORDER BY level ASC, name ASC
`

func (q *Queries) GetPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, getPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(&i.ID, &i.Name, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLeaveHistory = `-- name: InsertLeaveHistory :one
INSERT INTO leave_histories (leave_request_id, action, hrd_note, actor_id)
VALUES ($1, $2, $3, $4) RETURNING id, leave_request_id, action, hrd_note, actor_id, created_at
`

type InsertLeaveHistoryParams struct {
	LeaveRequestID int32          `json:"leave_request_id"`
	Action         string         `json:"action"`
	HrdNote        sql.NullString `json:"hrd_note"`
	ActorID        int32          `json:"actor_id"`
}

func (q *Queries) InsertLeaveHistory(ctx context.Context, arg InsertLeaveHistoryParams) (LeaveHistory, error) {
	row := q.db.QueryRowContext(ctx, insertLeaveHistory,
		arg.LeaveRequestID,
		arg.Action,
		arg.HrdNote,
		arg.ActorID,
	)
	var i LeaveHistory
	err := row.Scan(
		&i.ID,
		&i.LeaveRequestID,
		&i.Action,
		&i.HrdNote,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees SET full_name = $2, department = $3, position = $4, phone = $5 WHERE id = $1 RETURNING id, user_id, full_name, department, position, phone, joined_at
`

type UpdateEmployeeParams struct {
	ID         int32          `json:"id"`
	FullName   string         `json:"full_name"`
	Department string         `json:"department"`
	Position   string         `json:"position"`
	Phone      sql.NullString `json:"phone"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, updateEmployee,
		arg.ID,
		arg.FullName,
		arg.Department,
		arg.Position,
		arg.Phone,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.Phone,
		&i.JoinedAt,
	)
	return i, err
}

const updateLeaveType = `-- name: UpdateLeaveType :one
UPDATE leave_types SET name = $2, max_days = $3, description = $4 WHERE id = $1 RETURNING id, name, max_days, description
`

type UpdateLeaveTypeParams struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	MaxDays     int32          `json:"max_days"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateLeaveType(ctx context.Context, arg UpdateLeaveTypeParams) (LeaveType, error) {
	row := q.db.QueryRowContext(ctx, updateLeaveType,
		arg.ID,
		arg.Name,
		arg.MaxDays,
		arg.Description,
	)
	var i LeaveType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MaxDays,
		&i.Description,
	)
	return i, err
}
