// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Employee struct {
	ID         int32          `json:"id"`
	UserID     int32          `json:"user_id"`
	FullName   string         `json:"full_name"`
	Department string         `json:"department"`
	Position   string         `json:"position"`
	Phone      sql.NullString `json:"phone"`
	JoinedAt   sql.NullTime   `json:"joined_at"`
}

type LeaveBalance struct {
	ID            int32 `json:"id"`
	EmployeeID    int32 `json:"employee_id"`
	LeaveTypeID   int32 `json:"leave_type_id"`
	Year          int32 `json:"year"`
	TotalDays     int32 `json:"total_days"`
	UsedDays      int32 `json:"used_days"`
	RemainingDays int32 `json:"remaining_days"`
}

type LeaveRequest struct {
	ID          int32          `json:"id"`
	EmployeeID  int32          `json:"employee_id"`
	LeaveTypeID int32          `json:"leave_type_id"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     time.Time      `json:"end_date"`
	TotalDays   int32          `json:"total_days"`
	Reason      string         `json:"reason"`
	Status      string         `json:"status"`
	HrdNote     sql.NullString `json:"hrd_note"`
	ReviewedBy  sql.NullInt32  `json:"reviewed_by"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type LeaveType struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	MaxDays     int32          `json:"max_days"`
	Description sql.NullString `json:"description"`
}

type Notification struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Message   string       `json:"message"`
	IsRead    sql.NullBool `json:"is_read"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Role      string       `json:"role"`
	CreatedAt sql.NullTime `json:"created_at"`
}
