// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, message)
VALUES ($1, $2)
RETURNING id, user_id, message, is_read, created_at
`

type CreateNotificationParams struct {
	UserID  int32  `json:"user_id"`
	Message string `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification, arg.UserID, arg.Message)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationsByUser = `-- name: GetNotificationsByUser :many
SELECT id, user_id, message, is_read, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetNotificationsByUser(ctx context.Context, userID int32) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET is_read = TRUE
WHERE id = $1
RETURNING id, user_id, message, is_read, created_at
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id int32) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
