// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package db

import (
	"context"
	"database/sql"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (user_id, full_name, department, position, phone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, full_name, department, position, phone, joined_at
`

type CreateEmployeeParams struct {
	UserID     int32          `json:"user_id"`
	FullName   string         `json:"full_name"`
	Department string         `json:"department"`
	Position   string         `json:"position"`
	Phone      sql.NullString `json:"phone"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, createEmployee,
		arg.UserID,
		arg.FullName,
		arg.Department,
		arg.Position,
		arg.Phone,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.Phone,
		&i.JoinedAt,
	)
	return i, err
}

const getAllEmployees = `-- name: GetAllEmployees :many
SELECT id, user_id, full_name, department, position, phone, joined_at FROM employees
`

func (q *Queries) GetAllEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, getAllEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.Department,
			&i.Position,
			&i.Phone,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, user_id, full_name, department, position, phone, joined_at FROM employees
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id int32) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.Phone,
		&i.JoinedAt,
	)
	return i, err
}

const getEmployeeByUserID = `-- name: GetEmployeeByUserID :one
SELECT id, user_id, full_name, department, position, phone, joined_at FROM employees
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetEmployeeByUserID(ctx context.Context, userID int32) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByUserID, userID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.Department,
		&i.Position,
		&i.Phone,
		&i.JoinedAt,
	)
	return i, err
}
