// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leave.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createLeaveRequest = `-- name: CreateLeaveRequest :one
INSERT INTO leave_requests (employee_id, leave_type_id, start_date, end_date, total_days, reason, attachment_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, employee_id, leave_type_id, start_date, end_date, total_days, reason, status, hrd_note, reviewed_by, created_at, attachment_url
`

type CreateLeaveRequestParams struct {
	EmployeeID    int32          `json:"employee_id"`
	LeaveTypeID   int32          `json:"leave_type_id"`
	StartDate     time.Time      `json:"start_date"`
	EndDate       time.Time      `json:"end_date"`
	TotalDays     int32          `json:"total_days"`
	Reason        string         `json:"reason"`
	AttachmentUrl sql.NullString `json:"attachment_url"`
}

func (q *Queries) CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (LeaveRequest, error) {
	row := q.db.QueryRowContext(ctx, createLeaveRequest,
		arg.EmployeeID,
		arg.LeaveTypeID,
		arg.StartDate,
		arg.EndDate,
		arg.TotalDays,
		arg.Reason,
		arg.AttachmentUrl,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalDays,
		&i.Reason,
		&i.Status,
		&i.HrdNote,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.AttachmentUrl,
	)
	return i, err
}

const getAllLeaveRequests = `-- name: GetAllLeaveRequests :many
SELECT 
  lr.id,
  lr.employee_id,
  lr.leave_type_id,
  lr.start_date,
  lr.end_date,
  lr.total_days,
  lr.reason,
  lr.attachment_url,
  lr.status,
  lr.hrd_note,
  lr.reviewed_by,
  lr.created_at,
  e.full_name as employee_name,
  e.department as employee_department,
  e.position as employee_position
FROM leave_requests lr
JOIN employees e ON lr.employee_id = e.id
ORDER BY lr.created_at DESC
`

type GetAllLeaveRequestsRow struct {
	ID                 int32          `json:"id"`
	EmployeeID         int32          `json:"employee_id"`
	LeaveTypeID        int32          `json:"leave_type_id"`
	StartDate          time.Time      `json:"start_date"`
	EndDate            time.Time      `json:"end_date"`
	TotalDays          int32          `json:"total_days"`
	Reason             string         `json:"reason"`
	AttachmentUrl      sql.NullString `json:"attachment_url"`
	Status             string         `json:"status"`
	HrdNote            sql.NullString `json:"hrd_note"`
	ReviewedBy         sql.NullInt32  `json:"reviewed_by"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	EmployeeName       string         `json:"employee_name"`
	EmployeeDepartment string         `json:"employee_department"`
	EmployeePosition   string         `json:"employee_position"`
}

func (q *Queries) GetAllLeaveRequests(ctx context.Context) ([]GetAllLeaveRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllLeaveRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLeaveRequestsRow
	for rows.Next() {
		var i GetAllLeaveRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LeaveTypeID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalDays,
			&i.Reason,
			&i.AttachmentUrl,
			&i.Status,
			&i.HrdNote,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.EmployeeName,
			&i.EmployeeDepartment,
			&i.EmployeePosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLeaveTypes = `-- name: GetAllLeaveTypes :many
SELECT id, name, max_days, description FROM leave_types
`

func (q *Queries) GetAllLeaveTypes(ctx context.Context) ([]LeaveType, error) {
	rows, err := q.db.QueryContext(ctx, getAllLeaveTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveType
	for rows.Next() {
		var i LeaveType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MaxDays,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaveBalance = `-- name: GetLeaveBalance :many
SELECT id, employee_id, leave_type_id, year, total_days, used_days, remaining_days FROM leave_balances
WHERE employee_id = $1 AND year = $2
`

type GetLeaveBalanceParams struct {
	EmployeeID int32 `json:"employee_id"`
	Year       int32 `json:"year"`
}

func (q *Queries) GetLeaveBalance(ctx context.Context, arg GetLeaveBalanceParams) ([]LeaveBalance, error) {
	rows, err := q.db.QueryContext(ctx, getLeaveBalance, arg.EmployeeID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveBalance
	for rows.Next() {
		var i LeaveBalance
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LeaveTypeID,
			&i.Year,
			&i.TotalDays,
			&i.UsedDays,
			&i.RemainingDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaveRequestByID = `-- name: GetLeaveRequestByID :one
SELECT id, employee_id, leave_type_id, start_date, end_date, total_days, reason, status, hrd_note, reviewed_by, created_at, attachment_url FROM leave_requests
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLeaveRequestByID(ctx context.Context, id int32) (LeaveRequest, error) {
	row := q.db.QueryRowContext(ctx, getLeaveRequestByID, id)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalDays,
		&i.Reason,
		&i.Status,
		&i.HrdNote,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.AttachmentUrl,
	)
	return i, err
}

const getLeaveRequestsByEmployee = `-- name: GetLeaveRequestsByEmployee :many
SELECT id, employee_id, leave_type_id, start_date, end_date, total_days, reason, status, hrd_note, reviewed_by, created_at, attachment_url FROM leave_requests
WHERE employee_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetLeaveRequestsByEmployee(ctx context.Context, employeeID int32) ([]LeaveRequest, error) {
	rows, err := q.db.QueryContext(ctx, getLeaveRequestsByEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveRequest
	for rows.Next() {
		var i LeaveRequest
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.LeaveTypeID,
			&i.StartDate,
			&i.EndDate,
			&i.TotalDays,
			&i.Reason,
			&i.Status,
			&i.HrdNote,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.AttachmentUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeaveBalance = `-- name: UpdateLeaveBalance :one
UPDATE leave_balances
SET used_days = used_days + $2,
    remaining_days = remaining_days - $2
WHERE employee_id = $1 AND leave_type_id = $3 AND year = $4
RETURNING id, employee_id, leave_type_id, year, total_days, used_days, remaining_days
`

type UpdateLeaveBalanceParams struct {
	EmployeeID  int32 `json:"employee_id"`
	UsedDays    int32 `json:"used_days"`
	LeaveTypeID int32 `json:"leave_type_id"`
	Year        int32 `json:"year"`
}

func (q *Queries) UpdateLeaveBalance(ctx context.Context, arg UpdateLeaveBalanceParams) (LeaveBalance, error) {
	row := q.db.QueryRowContext(ctx, updateLeaveBalance,
		arg.EmployeeID,
		arg.UsedDays,
		arg.LeaveTypeID,
		arg.Year,
	)
	var i LeaveBalance
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.Year,
		&i.TotalDays,
		&i.UsedDays,
		&i.RemainingDays,
	)
	return i, err
}

const updateLeaveRequestStatus = `-- name: UpdateLeaveRequestStatus :one
UPDATE leave_requests
SET status = $2, hrd_note = $3, reviewed_by = $4
WHERE id = $1
RETURNING id, employee_id, leave_type_id, start_date, end_date, total_days, reason, status, hrd_note, reviewed_by, created_at, attachment_url
`

type UpdateLeaveRequestStatusParams struct {
	ID         int32          `json:"id"`
	Status     string         `json:"status"`
	HrdNote    sql.NullString `json:"hrd_note"`
	ReviewedBy sql.NullInt32  `json:"reviewed_by"`
}

func (q *Queries) UpdateLeaveRequestStatus(ctx context.Context, arg UpdateLeaveRequestStatusParams) (LeaveRequest, error) {
	row := q.db.QueryRowContext(ctx, updateLeaveRequestStatus,
		arg.ID,
		arg.Status,
		arg.HrdNote,
		arg.ReviewedBy,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.LeaveTypeID,
		&i.StartDate,
		&i.EndDate,
		&i.TotalDays,
		&i.Reason,
		&i.Status,
		&i.HrdNote,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.AttachmentUrl,
	)
	return i, err
}
